### ISSUE TITLE
logrotate-stream integration in bunyan

### ISSUE THREAD

**Issue by dmitrijs-balcers** [dstokes/logrotate-stream#3]
To avoid logrotation issues that comes with bunyan, I'm trying to tie up the application with this package. Unfortunateley I'm not able to make it to work. So I hope that you might help me.
This is the approach that I try to use (FAILING)
```javascript

var bunyan = require('bunyan'),
    stream = require('logrotate-stream'),
    toLogFile = stream({ file: './test.log', size: '100k', keep: 3 });

module.exports = bunyan.createLogger({

    name: 'appName',

    //src: true, // TODO: turn off in production

    serializers: bunyan.stdSerializers,

    streams: [
        {
            type: 'raw',
            level: 'trace',
            stream: toLogFile
        },

        {
            level: 'trace',
            stream: process.stdout
        }
    ]
});
```
And this is the error that I get:
```
0 master % NODE_ENV=dddd node backend | bunyan -l trace

events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Invalid non-string/buffer chunk
    at validChunk (_stream_writable.js:153:14)
    at LogStream.Writable.write (_stream_writable.js:182:12)
    at Logger._emit (/Users/user/Work/gitlab/appName/node_modules/bunyan/lib/bunyan.js:808:22)
    at Logger.trace (/Users/user/Work/gitlab/appName/node_modules/bunyan/lib/bunyan.js:891:24)
    at Socket.<anonymous> (/Users/user/Work/gitlab/appName/modules/someTool/tcp/start.js:26:17)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:117:20)
    at Object.afterConnect [as oncomplete] (net.js:887:10)
```

Could you please halp me to resolve the issue?

**Comment by dstokes** [comment]
@dmitrijs-balcers add `objectMode: true` to the logrotate-stream initializer options to fix

**Comment by dmitrijs-balcers** [comment]
Thank you, that fixed my issue!
